# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Message.delete_all
Promise.delete_all
Idea.delete_all
User.delete_all
Category.delete_all

Category.create!([{id: 1, name:'Technology'},{id: 2, name:'Games'},{id: 3, name:'Music'},{id: 4, name:'Design'}])

User.create!([
  {id: 1, first_name: "Admin", about: "Admin of TurnItOn", email: "admin@admin.com", password: "admin123", password_confirmation: "admin123", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2015-02-06 14:02:10", last_sign_in_at: "2015-02-06 14:02:10", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", admin: true},
  {id: 2, first_name: "Juan", last_name: "Soto", about: "I have a Bachelor's degree in Industrial Engineering from Purdue University, with fifteen years experience in the manufacturing industry. My passion is in solving problems and improving processes to streamline business, eliminate waste, and cut costs. I once saved my company $10 million through a single capacity analysis. I've been an integral part of certifying the Boeing 747, 767 and 777 for safety and FAA compliance. I'm looking for a position in the manufacturing industry as an Industrial Engineer.", birthdate: "1970-02-06", email: "juansoto@gmail.com", password: "clave123", password_confirmation: "clave123", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2015-02-06 14:02:10", last_sign_in_at: "2015-02-06 14:02:10", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1"},
  {id: 3, first_name: "Pedro", last_name: "Kraus", about: "I am a dedicated person with a family of four. I enjoy reading, and the knowledge and perspective that my reading gives me has strengthened my teaching skills and presentation abilities. I have been successful at raising a family, and I attribute this success to my ability to plan, schedule, and handle many different tasks at once. This flexibility will help me in the classroom, where there are many different personalities and learning styles.", birthdate: "1982-02-06", email: "pedroks@gmail.com", password: "clave123", password_confirmation: "clave123", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2015-02-06 14:03:01", last_sign_in_at: "2015-02-06 14:03:01", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1"},
  {id: 4, first_name: "Marta", last_name: "Gonzalez", about: "My name is Marta Gonzalez, and I enjoy meeting new people and finding ways to help them have an uplifting experience. I have had a variety of customer service opportunities, through which I was able to have fewer returned products and increased repeat customers, when compared with co-workers. I am dedicated, outgoing, and a team player. Who could I speak with in your customer service department about your organization’s customer service needs?", birthdate: "1986-02-06", email: "marta22@gmail.com", password: "clave123", password_confirmation: "clave123", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2015-02-06 14:03:44", last_sign_in_at: "2015-02-06 14:03:44", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1"}])

Idea.create!([{id: 1, title:"Sport headphones", description: 'Confortable headphones made for all kind of sports.', estimated_date: nil, goal_amount: 10000, category_id: 3, user_id: 2, idea_image_file_name: "img1.jpg", created_at: "2017-05-25 14:53:19"},{id: 2, title:"Light shoes", description: 'Best running shoes on the market.', estimated_date: nil, goal_amount: 500, category_id: 4, user_id: 3, idea_image_file_name: "img2.jpg", created_at: "2018-03-25 14:53:19"},{id: 3, title:"Perfect controller", description: 'Perfect for gamers.', estimated_date: nil, goal_amount: 20000, category_id: 2, user_id: 4, idea_image_file_name: "img3.jpg", created_at: "2018-05-25 14:53:19"},{id: 4, title:"Supermarket GPS", description: "You'll never have to ask for a product location again.", estimated_date: nil, goal_amount: 90000, category_id: 1, user_id: 1, idea_image_file_name: "img4.jpg"}])

Message.create!([{id: 1, content: "Nice shoes man! ", idea_id: 2, user_id: 4, created_at: "2018-05-25 20:19:37", updated_at: "2018-05-25 20:19:37"}, 
{id: 2, content: "I want to try it already! ", idea_id: 3, user_id: 2, created_at: "2018-04-15 23:11:37", updated_at: "2018-04-15 23:11:37"},
{id: 3, content: " Very useful when skydiving! ", idea_id: 1, user_id: 3, created_at: "2017-05-25 03:19:17", updated_at: "2017-05-25 03:19:17"},
{id: 4, content: " I lost my kid at the supermarket today, can I find him with this? LOL ", idea_id: 4, user_id: 4, created_at: "2018-04-20 16:20:37", updated_at: "2018-04-20 16:20:37"},
{id: 5, content: "Very funny Marta, you better fund this idea! ", idea_id: 4, user_id: 3, created_at: "2018-04-21 20:19:37", updated_at: "2018-04-21 20:19:37"},
{id: 6, content: "Can't wait for these!", idea_id: 2, user_id: 2, created_at: "2018-10-07 20:19:37", updated_at: "2018-10-07 20:19:37"},
{id: 7, content: "Fortnite would be awesome to be played with this!", idea_id: 3, user_id: 1, created_at: "2018-02-15 20:19:37", updated_at: "2018-02-15 20:19:37"} ])

Promise.create!([{id: 1, title: "Play Station II", description: "Duis in leo quis sem imperdiet sagittis. Pellentesque elementum finibus massa tincidunt tempor. Nullam elementum venenatis dolor sit amet semper. Duis luctus non sapien in malesuada. Nulla facilisi. Etiam nibh mi, sagittis non velit a, porta pulvinar odio. Duis vel libero fermentum, eleifend ligula et, hendrerit ante.", cost: 1500, idea_id: 3, user_id: 4, created_at: "2018-05-25 20:44:21", updated_at: "2018-05-25 20:44:21"},
{id: 2, title: "Play Station Account", description: "Pellentesque pulvinar felis sit amet tellus porttitor, vel interdum metus sagittis. Curabitur facilisis urna at rutrum volutpat. Aliquam consequat congue enim eget finibus. Donec fringilla lorem vel eros bibendum mollis. Proin varius ornare massa sit amet sollicitudin. Cras lacinia est eros, vel blandit velit eleifend vel.", cost: 20, idea_id: 3, user_id: 4, created_at: "2018-05-25 20:53:03", updated_at: "2018-05-25 20:53:03"},
{id: 3, title: "River vs Boca tickets", description: "Integer tempor euismod nisl sed aliquam. Donec posuere ante id ligula fringilla fermentum. Sed non imperdiet elit. Etiam nec nisl vel metus scelerisque varius. Aliquam ornare lectus a ante malesuada vestibulum. Aliquam viverra vulputate sem, facilisis posuere ligula euismod nec.", cost: 50, idea_id: 2, user_id: 3, created_at: "2018-05-25 20:55:12", updated_at: "2018-05-25 20:55:12"},
{id: 4, title: "Be the first one to have your shoes!", description: "Nulla viverra commodo nisi vitae suscipit. Phasellus mollis vestibulum mauris ut mollis. Fusce quis malesuada justo. Ut venenatis tellus quam, vel sodales elit rhoncus nec. Pellentesque et neque suscipit, lobortis turpis sit amet, luctus augue. Suspendisse vestibulum suscipit laoreet. Vestibulum a rutrum arcu, eget dictum magna.", cost: 300, idea_id: 2, user_id: 3, created_at: "2018-05-25 20:56:22", updated_at: "2018-05-25 20:56:22"},
{id: 5, title: "Spotify Premium Account", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam lectus quam, convallis vitae massa ut, feugiat pellentesque urna. Pellentesque maximus velit laoreet risus facilisis maximus. Integer scelerisque, nibh quis vulputate blandit, dui ipsum laoreet eros, sit amet elementum orci magna sed nibh. ", cost: 15, idea_id: 1, user_id: 2, created_at: "2018-05-25 20:58:03", updated_at: "2018-05-25 20:58:03"},
{id: 6, title: "Bad Bunny Tickets", description: "Morbi id lorem sit amet turpis ornare luctus non ut sem. Etiam gravida dui eleifend, mollis justo eget, sollicitudin dolor. In consectetur tincidunt tortor et sagittis. Praesent facilisis rhoncus lacus vel rhoncus. Pellentesque fermentum mauris nec elit pretium, quis iaculis enim tincidunt. ", cost: 85, idea_id: 1, user_id: 2, created_at: "2018-05-25 20:59:33", updated_at: "2018-05-25 20:59:33"},
{id: 7, title: "30% off on your next supermaket visit", description: " Nunc ut aliquet diam, eu vestibulum sapien. Nulla viverra commodo nisi vitae suscipit. Phasellus mollis vestibulum mauris ut mollis. Fusce quis malesuada justo. Ut venenatis tellus quam, vel sodales elit rhoncus nec. Pellentesque et neque suscipit, lobortis turpis sit amet, luctus augue.", cost: 150, idea_id: 4, user_id: 1, created_at: "2018-05-25 21:01:12", updated_at: "2018-05-25 21:01:12"},
{id: 8, title: "Chilean wine", description: "Cras ac diam tristique, laoreet dui in, mattis orci. Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras sapien est, semper eu ante ut, cursus tristique quam. Quisque eu neque odio. Sed et iaculis eros. Phasellus suscipit sapien ac fermentum venenatis.", cost: 200, idea_id: 4, user_id: 1, created_at: "2018-05-25 21:02:07", updated_at: "2018-05-25 21:02:07"} ])


